### PR TITLE
upgrade coderstephen/slack-client from 0.1.* to 0.2.*

### PR DESCRIPTION
**Pull request by pavel-voronin**

### CODE REVIEW

**Comment by sagebind** [comment]
A lot of stuff going on here. A few comments:
1. Why the move from `src/` to `app/`? Seems a little unnecessary, since `src/` is pretty standard.
2. Why do you change the package name to `pavel-voronin/slackyboy` if you are merging into my repo? If you want to keep the official repository at `coderstephen/slackyboy`, then then package name should remain `coderstephen/slackyboy`.
   If you want to take the package over, I might be OK with that, but then I would move this repo to your user account, and `coderstephen/slackyboy` would be the fork.
3. Similar discussion as above for the Gitter chat room.
4. Why remove the other plugins?
5. I like your idea of simply logging to STDOUT. Probably more useful and efficient.
6. Glad you added an example config.

So the main issue is really the ownership of the repository.

Thanks for spending time to contribute, by the way!

**Comment by david-duncan** [comment]
In addition to what you brought up there there were some interesting style things that are rather minor.

some files the line break was kept after <?php and some files the namespace was squashed into the <?php  line

I guess I don't have a preference for either style even though PSR2 advocates it being on the next line, but it should at least be consistent

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#3-namespace-and-use-declarations

**Comment by sagebind** [comment]
For that case, I think sticking to PSR-2 and putting the namespace after a line break is probably better.

**Comment by pavel-voronin** [comment]
First of all, I am sorry for misunderstanding!

I created PR when it was just `upgrade coderstephen/slack-client from 0.1.* to 0.2.*` (fbefe44), all the other stuff are just my experiments in my own environment.

I have some thoughts about what architecture would be fine for general purposes so I am moving in that direction. **_If_** I will achieve my goal, I will share. :)

I am going to close this pull request and will make other.

Answers:

@coderstephen 
1. I cannot agree that this bot application is a library and should be required by other applications. I think this is a stand-alone application; furthermore, I consider slackyboy should be a sort of framework. My main framework is Laravel and it uses `app` as main application folder. It is just a tribute. :)
2. I'm sorry for that, this is just a wrong pull request.
3. The same.
4. I think all other plugins (except AdminControl one maybe) are not demonstrative enough so I moved out them from my environment.

@david-duncan 

PSR-2 have no opinion about where to put `namespace`. In examples PSR-2 authors place it _after_ the `<?php` at the new line but don't tell that I SHOULD or MUST do the same. Some coders (like @JeffreyWay by the way) use this notation, so am I. :)

**Pull request closed without merging**
